import type { CashFlowProjectionItem, RecurringTransaction } from '../types'

export function summarizeCashFlowPlan(
  recurring: RecurringTransaction[],
  items: CashFlowProjectionItem[],
) {
  const activeRules = recurring.filter((rule) => rule.is_active)
  return {
    ruleCount: activeRules.length,
    incomeRuleCount: activeRules.filter((rule) => rule.type === 'credit').length,
    expenseRuleCount: activeRules.filter((rule) => rule.type === 'debit').length,
    projectedIncome: items
      .filter((item) => item.type === 'credit')
      .reduce((sum, item) => sum + item.amount_primary, 0),
    projectedExpenses: items
      .filter((item) => item.type === 'debit')
      .reduce((sum, item) => sum + item.amount_primary, 0),
  }
}

export function projectionSourceKey(item: CashFlowProjectionItem) {
  if (item.source === 'credit_card') return 'cardDue'
  if (item.source === 'booked') return 'booked'
  return item.auto_generate ? 'autoGenerated' : 'planned'
}

export interface CashFlowDisplayMovement {
  key: string
  date: string
  description: string
  amountPrimary: number
  type: 'debit' | 'credit'
  sourceKey: string
  accountName: string
  itemCount: number
  confidence: CashFlowProjectionItem['confidence']
  installmentNumber: number | null
  totalInstallments: number | null
}

export function groupCashFlowMovements(
  items: CashFlowProjectionItem[],
): CashFlowDisplayMovement[] {
  const movements = new Map<string, CashFlowDisplayMovement>()

  for (const item of items) {
    const isCardBill = item.source === 'credit_card'
    const key = isCardBill
      ? `card:${item.account_id}:${item.date}`
      : `item:${item.recurring_id ?? item.transaction_id ?? `${item.date}:${item.description}`}`
    const existing = movements.get(key)
    if (existing) {
      existing.amountPrimary += item.amount_primary
      existing.itemCount += 1
      continue
    }
    movements.set(key, {
      key,
      date: item.date,
      description: item.description,
      amountPrimary: item.amount_primary,
      type: item.type,
      sourceKey: projectionSourceKey(item),
      accountName: item.account_name,
      itemCount: 1,
      confidence: item.confidence,
      installmentNumber: item.installment_number,
      totalInstallments: item.total_installments,
    })
  }

  return [...movements.values()].sort((a, b) =>
    a.date.localeCompare(b.date) || a.description.localeCompare(b.description)
  )
}
